### ISSUE TITLE
Git Bash can't run .bat programs

### ISSUE THREAD

**Issue by mcandre** [msysgit/msysgit#101]
Many command line programs are written as .bat MS-DOS batch files (e.g. Chocolatey NuGet). You call them as you would .exe's, normally omitting the extension.

Unfortunately, these .bat files are not available inside Git Bash shells, as Git Bash fails to look them up as it does .exe's. Even when PATH is set properly, Git Bash throws its hands up as to where a batch program lies.

When the absolute path to a batch program is specified, Git Bash does find the program, but fails to run it properly, as it does not know how to handle the MS-DOS batch syntax. What Git Bash should do instead is recognize that these files are in a different programming language, and call the appropriate interpreter, in this case cmd.exe.

Could we please add .bat program support to Git Bash by correcting these two behaviors?

**Comment by kevmuret** [comment]
A way to make it work is to create a `.exe` file with the same name and simply write a call usign the complete path and redirect arguments with `"$@"`.

Example to make `script.bat` running as script you create a file named `script.exe` with the following content :
`/path/to/script.bat "$@"`

And it will work 👍

**Comment by dscho** [comment]
Please note that Git for Windows 1.x (for which msysgit is the development environment) was retired in August 2015. The successor is https://github.com/git-for-windows/.
