### ISSUE TITLE
Support for perforce

### ISSUE THREAD

**Issue by bond-** [msysgit/msysgit#108]
The latest git 1.8.1.2 output for git-p4 is:

`$ git p4
fatal: git was built without support for git-core\git-p4 (NO_PYTHON=YesPlease).
rlokinen@RLOKINEN-LAP /usr (master)`

Please add documentation if this is supported. Thanks in advance.

**Comment by hickford** [comment]
See also https://github.com/git-for-windows/git/issues/594
