### ISSUE TITLE
Cloning an empty remote repository using Git GUI fails.

### ISSUE THREAD

**Issue by mhalenza** [msysgit/msysgit#144]
Using the Git GUI "Clone Existing Repository" option to clone an empty repository fails with "fatal: Couldn't find remote ref HEAD" then "fatal: The remote end hung up unexpectedly".  Using Git Bash to run the equivalent "git clone" command succeeds just fine.

Other info:
OS: Windows 7
Git Version: 1.8.3 and 1.8.4
Git GUI Version: 0.17 and 0.18
(Git installed from https://code.google.com/p/msysgit/downloads/list)

**Comment by gnalbandian** [comment]
this is stil happening

**Comment by dscho** [comment]
@gnalbandian @kusma's advice to report this to upstream Git is still valid, too.
