### ISSUE TITLE
Random "cygwin heap" failures on Windows 8.1

### ISSUE THREAD

**Issue by dolmen** [msysgit/msysgit#194]
I get random "cygwin heap" failures with git-1.9.2-preview20140411.exe on Windows 8.1.
Running the same command again usually work.

Here is an example (I got a few others today):

```
C:\Outils\msysgit\src\perl>git push -u dolmen msys-perl--use-update-lib
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x4A0000, State 0x10000
C:\Program Files (x86)\Git\bin\ssh.exe: *** Couldn't reserve space for cygwin's
heap, Win32 error 0
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Outils\msysgit\src\perl>git push -u dolmen msys-perl--use-update-lib
Counting objects: 37, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (16/16), 1.90 KiB | 0 bytes/s, done.
Total 16 (delta 10), reused 0 (delta 0)
To dolmen.github.com:dolmen/msysgit.git
 * [new branch]      msys-perl--use-update-lib -> msys-perl--use-update-lib
Branch msys-perl--use-update-lib set up to track remote branch msys-perl--use-up
date-lib from dolmen.
```

**Comment by krystufe** [comment]
Hi, I get same behavior on Windows8.1 with Git-1.9.5-preview20150319.exe (also with Git-1.9.4-preview20140611.exe). I tried zainengineer's advice (http://stackoverflow.com/questions/18502999/git-extensions-win32-error-487-couldnt-reserve-space-for-cygwins-heap-win32) but it does not work.
Please help, I am getting desperate.

**Comment by dscho** [comment]
@krystufe try the spanking new sneak preview of Git for Windows 2.x (64-bit): https://git-for-windows.github.io/. The 64-bit address range is large enough that we will hopefully never encounter that heap problem again.

**Comment by krystufe** [comment]
@dscho Thanks a lot! It works like clock.
