### ISSUE TITLE
Git GUI: Unicode paths misinterpreted since 1.9.0

### ISSUE THREAD

**Issue by peci1** [msysgit/msysgit#206]
When I upgraded from 1.8.5.2 to 1.9.0, Git GUI stopped working with repositories containing non-ASCII characters in their path.

E.g. a repo stored in `D:\Programování\git-tutorial` could be loaded in 1.8, but in 1.9 I instead just see an error saying:

    No working directory D:/ProgramovĂˇnĂ­/git-tutorial
    couldn't change working directory
    to "D:/ProgramovĂˇnĂ­/git-tutorial": no such file or
    directory 

Git GUI itself starts without problems, but when I try to open the repo, this error appears. Downgrading to 1.8 fixes the issue.

**Comment by dscho** [comment]
Happily, in [Git for Windows 2.x](http://git-for-windows.github.io/) we already have Tcl/Tk 8.6. And since 2.x supersedes 1.x, I close the ticket here: With versions 2.x, Git for Windows moved to [a new org](https://github.com/git-for-windows/).
