### ISSUE TITLE
Is it possible to do a silent install?

### ISSUE THREAD

**Issue by BrianGilbert** [msysgit/msysgit#222]
Is there a way to execute the installer feeding it flags for what would normally be asked.. eg silent installation..?

**Comment by lklepner** [comment]
I found the wiki page to be empty -
https://github.com/msysgit/msysgit/wiki/Silent-Installation

**Comment by dscho** [comment]
@lklepner have you seen the first revision of said page? It looks a bit more complete to me than the current revision: https://github.com/msysgit/msysgit/wiki/Silent-Installation/_compare/c882fe542e1ee873935b69cfbe508f0c153bab3c...442206b4d6bd07735da6faf10fa4e0ab6a024ecc

**Comment by lklepner** [comment]
That one is better - thanks for bringing it to my attention. I've brought the missing elements into the latest version.
