### ISSUE TITLE
git over HTTPS hangs if behind a proxy

### ISSUE THREAD

**Issue by MattTW** [msysgit/msysgit#23]
msysgit 1.7.10 hangs when performing operations over https behind a proxy.  http works fine.    Downgrading to 1.7.9 also works.    

The issue is detailed in these links:

http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=627335
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=671827

Looks like there are new releases of curl/libcurl that have this fixed.   Can we get these incorporated into msysgit?

Thanks!

**Comment by marsoltys** [comment]
I got the same under Git 2.5.3 (64 bit).

It hangs when I do git pull from bitbucket.

It asks me for password to bitbucket and then just hangs.

Weird thing is that configuration which I have works perfectly for Git 1.9.0 and 1.9.5

Any clues ?

VERBOSE:

* Couldn't find host bitbucket.org in the _netrc file; using defaults
* Found bundle for host bitbucket.org: 0x580940
* NTLM-proxy picked AND auth done set, clear picked!
* timeout on name lookup is not supported
* Hostname proxy.xxxxxxxxxxx was found in DNS cache
*   Trying xxxxxxxxxxx...
* Connected to proxy.xxxxxxxxxxx (xxxxxxxxxxx) port 8080 (#2)
* Establish HTTP proxy tunnel to bitbucket.org:443
* Server auth using Basic with user 'xxxxxxxxx'
> CONNECT bitbucket.org:443 HTTP/1.1
Host: bitbucket.org:443
User-Agent: git/2.5.3.windows.1
Proxy-Connection: Keep-Alive

< HTTP/1.1 407 Proxy Authentication Required
< Proxy-Authenticate: NTLM
< Proxy-Authenticate: BASIC realm="xxxxxxx"
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Proxy-Connection: close
< Connection: close
< Content-Length: 849
<
* Ignore 849 bytes of response-body
* Connect me again please
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* SSL re-using session ID
* Unknown SSL protocol error in connection to bitbucket.org:443
* Closing connection 2

**Comment by linquize** [comment]
If the problem is still valid to git for windows 2.x, please report to 
https://github.com/git-for-windows/git/issues
