### ISSUE TITLE
upload-pack spews tons of data

### ISSUE THREAD

**Issue by ethomson** [msysgit/msysgit#247]
`upload-pack` emits keep-alive packets as quickly as possible (ignoring `uploadpack.keepalive` configuration setting), as long as `pack-objects` is running.  On a large repository, this can add up to megabytes worth of useless keep-alive packets:

`compat/poll/poll.c` here is deficient and has a loop to remove any `pollfd`s that had events that were not requested by the caller.  If no `pollfd`s remain interesting after this loop, it happily returns 0, which is documented as having reached the timeout.  (Instead, `poll` should not return until either it has something interesting on a `pollfd` or the timeout is *actually* reached.)  As a result, we `upload-pack` expects that the timeout has been reached (when in fact nothing has happened at all) and sends a keep-alive packet.

A fix (cherry-picked onto msysgit/git) is at https://github.com/ethomson/git/commits/compat_poll.

I wanted to open an issue here for visibility, but I am not opening a pull request against msysgit because:

1. You consume git as a submodule and I have no idea how to open a PR that makes any sense at all against a submodule.  I suspect there is not one.
2. It seems like the "right thing" to do here is to fix this in gnulib.  This is terribly regrettable, since gnulib doesn't seem to play well in msys.

If anybody has actually gotten gnullib building and the tests running in msys, I would love an idea of how to proceed.

**Comment by t-b** [comment]
@ethomson Any update here?

**Comment by ethomson** [comment]
Sadly, no.  I will not be able to continue to move this patch forward into gnulib directly, since the FSF's employer agreements have an overly broad patent grant.  It's disappointing that end users get harmed with such views.  Especially for a ten line bug fix.  Alas.

Please let me know how you would like me to proceed.  I would love somebody to take that patch to gnulib and move it forward:  I would be happy to place it into the public domain and / or assign copyrights to anyone who wants to take care of it.  Or I can spin up an update PR with that patch if you only want to update git and not upstream as well.

**Comment by t-b** [comment]
@ethomson Thanks for trying. I'm working solo so I'm even less inclined reading and understanding english legalese documents.

So I would suggest that we intergrate your gnulib-patches into https://github.com/git-for-windows/git (master branch) for now. Please indicate in the commit message that you place the changes into the public domain. Then we can, at some later point, try to get them into gnulib upstream.

**Comment by ethomson** [comment]
Sorry about the exceptional delay, please see https://github.com/msysgit/git/pull/330

**Comment by ethomson** [comment]
Fixed via https://github.com/msysgit/git/pull/330 - thanks!

**Comment by dscho** [comment]
This fix made it into the most recent 1.9.5 release.
