### ISSUE TITLE
Remove current directory shortcut from default PATH

### ISSUE THREAD

**Issue by gonuke** [msysgit/msysgit#248]
The default bash configuration includes the current directory: `.` in the PATH.

Perhaps this is a matter of preference, but many believe this to be a dangerous practice and prefer to require users to explicitly refer to the current directory if they are going to execute something in the current directory.

(Apologies if this has been discussed before.)

**Comment by sschuberth** [comment]
I finally made up my mind about this and decided to address this for the upcoming "Git SDK"-based version of Git for Windows.

**Comment by dscho** [comment]
We addressed this in the installer of [Git for Windows 2.x](http://git-for-windows.github.io/): `.` is no longer in the `PATH`. However, that was not enough, we needed two follow-up patches:

- [for the installer](https://github.com/git-for-windows/build-extra/commit/db815ec7a782b1191c8e8932c5cd0063f41d0823) and
- [for the portable version](https://github.com/git-for-windows/build-extra/commit/6e83a100c95d1c7f963ccb66ab38f95171256a00)

Thanks to everybody who helped resolve this issue.
