### ISSUE TITLE
installer - Windows Explorer integration has to kill ssh-agent process

### ISSUE THREAD

**Issue by mathieuroche** [msysgit/msysgit#249]
Hello, 

On Windows 7, I have a problem to install git with chocolatey (http://chocolatey.org).
Currently, the maintainer (@ferventcoder) has removed explorer integration of this package because of the following error:
"The process cannot access the file because it is being used by another process."
In fact, it's due to ssh-agent process which block the installation.

You can find more information here:
- https://groups.google.com/forum/#!msg/chocolatey/ewnCrG_q_bM/xeJZGDQIZMgJ
- http://chocolatey.org/packages/git

Thanks.

**Comment by dscho** [comment]
@ferventcoder if you are still interested in letting `/CLOSEAPPLICATIONS` close `ssh-agent`, please [open a new issue with Git for Windows 2.x](http://git-for-windows.github.io/#contribute). In that case, please note that I will ask for your assistance in resolving the issue. Thanks!
