### ISSUE TITLE
Fails with Exception: STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by vitkhudenko** [msysgit/msysgit#25]
After upgrading from Git-1.6.5.1-preview20091022 to Git-1.7.10-preview20120409 my git has stoped working. For instance, when I try to open bash I get the following bash.exe.stackdump:

    MSYS-1.0.12 Build:2011-07-20 17:52
    Exception: STATUS_ACCESS_VIOLATION at eip=6801364A
    eax=00005009 ebx=00005009 ecx=7C80EEF7 edx=00000000 esi=0022FE34 edi=0022FA34
    ebp=0022F8A4 esp=0022F88C program=C:\Program Files\Git\bin\bash.exe
    cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
    Stack trace:
    Frame     Function  Args
    0022F8A4  6801364A  (00005009, 00000000, 00110000, 00000000)
      12193 [main] bash 4092 handle_exceptions: Exception: STATUS_ACCESS_VIOLATION
      12848 [main] bash 4092 handle_exceptions: Error while dumping state (probably corrupted stack)

Reverting back to Git-1.6.5.1-preview20091022 restores normal functioning.

I'm on Win XP Pro + SP3.

**Comment by RouR** [comment]
I have the same issue - How to fix it?
(Russian windows, using R:\TEMP value for %TEMP% and %TMP% in Windows settings, using SoftPerfect RAM Disk to store my temp on disk R:.)

**Comment by a-iv** [comment]
@RouR just use NTFS :)

**Comment by egocarib** [comment]
I'm having this issue, and it's quite frustrating. After a lot of internet searching there really is almost no good info about a solution for this issue. I also can't figure out where to download an older version of GitHub for windows (this problem started for me recently after an upgrade)

here's the error I get:
MSYS-1.0.12 Build:2012-07-05 14:56
Exception: STATUS_ACCESS_VIOLATION at eip=006B7968
eax=00000001 ebx=0028F0AC ecx=00734C5C edx=00350000 esi=0028F0B0 edi=00000000
ebp=0028F084 esp=0028EF0C program=C:\Users\<username>\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\sh.exe
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028F084  006B7968  (00000000, 000000B0, 0028F0C8, 0028F52C)
End of stack trace

dscho wrote:
> Okay, so the resolution seems to be (from what little information is provided) solved by using rebase.exe [as described here](http://www.trinitycore.org/f/topic/5194-msysgit-couldnt-reserve-space-for-cygwins-heap/).

The link is broken, though, so this isn't a very helpful solution.

Also, jianwubayiba wrote:
> replace msys-1.0.dll by a new one in "documents and settings\administrator\local setting\application data\github\portablegit_xxxx..."

But it's unclear where to get the "new one" from. Where can I download it and which version should I download?

I'd really appreciate some help with this issue. I'm on Windows 8.1. Please let me know if you need more information from me. This error is entirely preventing me from syncing my repository, so it's a real showstopper.

**Comment by dscho** [comment]
> dscho wrote:
> 
> > Okay, so the resolution seems to be (from what little information is provided) solved by using rebase.exe as described here.
> 
> The link is broken, though, so this isn't a very helpful solution.

There is also a [Dr Dobb's article about `rebase.exe`](http://www.drdobbs.com/windows/optimizing-dll-loads/184416922) that you might find helpful. The idea being to call `cmd.exe` (i.e. *not* any MSys program such as `bash.exe`), switch working directory to the top-level directory of Git for Windows (which is not quite the same as Git*Hub* for Windows, BTW :grinning:) and then execute something like

```cmd
mingw\bin\rebase.exe -b 0x60000000 bin\*.dll
```

You might also find that using the upcoming [Git for WIndows 2.x](https://git-for-windows.github.io/) may address your woes.

**Comment by dscho** [comment]
Git for Windows 1.x was retired, in favor of [Git for Windows 2.x](https://git-for-windows.github.io/). Therefore I close this ticket, asking you to [open another one](https://git-for-windows.github.io/#contribute) if the bug persists. Thank you.
