### ISSUE TITLE
Git-GUI: Language cannot be changed

### ISSUE THREAD

**Issue by tzaeschke** [msysgit/msysgit#255]
On my Windows 7 system, git-hui (0.19.GITGUI) always comes up in German.
I would like to propose to have a language setting in the git-gui Options dialogue.

Some reasons:
1) Language auto-detection?
This is probably not what all users want. The German translation is not necessarily bad, but it introduces new terms for 'pull', 'fetch' and so on. There is no way to find out what they mean other than trying them out (I'm German but I really can't tell). It also adds another set of terminology to learn.

2) A bug? 
Windows 7 itself is English, so are most other installed applications. So maybe this is actually a bug, but even though my Windows is English, it somehow switches to German.

3) Consistency
While git-gui is in German, git-bash comes up in English as expected. As mentioned above, the conflicting terminology doesn't makes it quite hard to use. 

I actually tries some workaround, such as adding `@set LANG=en` to `gitk.cmd`, but it doesn't seem to have any effect.
If there is a decision to not touch the software, could there at least be an entry in the FAQ on how to work around this problem?

**Comment by PetterBomban** [comment]
Deleting all the files in the folder AssarBubbla posted fixes the problem. Thanks!

**Comment by valerypetit** [comment]
nothing work for me, i have the version 2.5.1
someone know why???

**Comment by dscho** [comment]
> i have the version 2.5.1

Then you are using the wrong bug tracker.

> nothing work for me

If you want excellent help, I suggest to write an excellent bug report. Git for Windows 2.x' guide lines to do that can be found here: https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines
