### ISSUE TITLE
Garbled text on scrolling through command outputs

### ISSUE THREAD

**Issue by SalmanPK** [msysgit/msysgit#257]
Demo:-
![msysgitbug](https://cloud.githubusercontent.com/assets/337125/4781513/b449be58-5ca3-11e4-9340-d503cd2bb22b.gif)

**Comment by dscho** [comment]
I had kind of hoped that a [Minimal, Complete and Verifiable Example](http://stackoverflow.com/help/mcve) would materialize in the meantime. A screencast is just not a very good substitute.

Anyway, if this problem persists with [Git for Windows 2.x](http://git-for-windows.github.io/), I *strongly* advise to follow the hints in https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines to make a but report that would allow for example me to reproduce the problem.
