### ISSUE TITLE
wincred credential helper doesn't work when e-mail used as a user name

### ISSUE THREAD

**Issue by AlexeyKryshen** [msysgit/msysgit#258]
For some reason if e-mail used as a username (I was working with Github, unfortunately have no other repos to test) wincred doesn't work: while credentials are stored in Windows, git continue to ask credentials. In order to get the wincred helper work for Github I have to use the my normal Github username, not e-mail. Maybe there is problem with multiple '@' symbols in URL used if e-mail is used as username ? Because credentials are actually stored but not used, it seems that key used to store credential and one used to retrieve are different for some reason (escaped/not escaped '@' ?)

**Comment by linquize** [comment]
Did you test with https://github.com/git-for-windows/git 2.4?

**Comment by huerlisi** [comment]
I just tested on the newest git-for-windows release candidate. Still not working.

**Comment by huerlisi** [comment]
Sorry, it actually worked!

:+1:

**Comment by dscho** [comment]
@huerlisi please feel free to close tickets yourself when the associated problems are addressed.

**Comment by rofrol** [comment]
wincred doesn't work for me. Works with `%40` and `store`

     git config --global credential.helper store

**Comment by CrescentFresh** [comment]
Running TG 2.4.0.2, still can't use my email as my username, I keep getting prompted.

Switch to my username that does not include @, and works as expected.

**Comment by dscho** [comment]
The msysGit project is unmaintained since Git for Windows 2.5.0 was released. If you have questions or bug reports that are not Windows-specific, it would be better to report them to [the Git mailing list](mailto:git@vger.kernel.org) instead.
