### ISSUE TITLE
Slow Git in Vietnam

### ISSUE THREAD

**Issue by DominikMostek** [msysgit/msysgit#260]
After i arrived to Vietnam (from Czech Rep.) git started to be very slow (by very slow i mean 3+ minutes for basic things like git stash/add). It was matter of seconds before.
I confirmed it with my colleague who was in VN week earlier and he had same issue and after returning to the CZ everything is ok again. 
I am using  Git (version 1.9.0-preview20140217)

**Comment by EmilMoe** [comment]
I must say I have the same experience. Have been living in Cambodia for 7 months, where I had no problems, now I'm in Vietnam and have to use a SSH tunnel to be able to reach Github. It can only be a limitation somewhere.

**Comment by dscho** [comment]
@EmilMoe maybe you can make use of [my comment](https://github.com/msysgit/msysgit/issues/260#issuecomment-62695911)?
