### ISSUE TITLE
Out of Memory error when performing a Git GC

### ISSUE THREAD

**Issue by strich** [msysgit/msysgit#268]
We have a fairly large repo with a lot a large binary files (Up to 20MB) and it is now at the point where any kind of git gc will crash and run out of memory. I believe it is because the git binary is 32bit and runs out of addressable space.

Is there no 64bit Git binary for Windows?

**Comment by dscho** [comment]
@strich not that there was any help from your side, but we do have 64-bit Git for Windows 2.x now.
