### ISSUE TITLE
msysgit can't build 64-biy git-cheetah out of the box

### ISSUE THREAD

**Issue by SamB** [msysgit/msysgit#271]
I'm really not sure how I'm supposed to build the 64-bit version of git-cheetah, since doing the not-quite-obvious thing results in this:

```
Sam@SAM-LAPTOP /src/git-cheetah (master)
$ make W64=y
make -C explorer all
make[1]: Entering directory `/src/git-cheetah/explorer'
make -C ../common all
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
make[2]: Entering directory `/src/git-cheetah/common'
make[2]: Leaving directory `/src/git-cheetah/common'
/src/mingw-w64/sysroot/bin/x86_64-w64-mingw32-windres -o cheetah.o -i cheetah.rc
make[1]: /src/mingw-w64/sysroot/bin/x86_64-w64-mingw32-windres: Command not found
make[1]: *** [cheetah.o] Error 127
make[1]: Leaving directory `/src/git-cheetah/explorer'
make: *** [all] Error 2
```

And <https://github.com/msysgit/msysgit/wiki/GitCheetah> says nothing about 64-bit builds.

**Comment by dscho** [comment]
Seems that you did not run the `install-easy.sh` and `install-zlib.sh` scripts in `/src/mingw-w64/`.

**Comment by linquize** [comment]
The script should download mingw-w64 (~360MB) and unzip to `/src/mingw-w64/`

**Comment by SamB** [comment]
@dscho @linquize: I don't seem to have those scripts, but perhaps you meant `release-easy.sh` and `release-zlib.sh`?

**Comment by dscho** [comment]
@SamB yep, those scripts were meant.

However, we switched to [a new development environment](http://git-for-windows.github.io/#download-sdk), and I also just spent some time to fix building Git Cheetah in that environment. With that, I declare this bug resolved (finally!).
