### ISSUE TITLE
Long path names on Windows

### ISSUE THREAD

**Issue by EvilBeaver** [msysgit/msysgit#276]
When full filename (with path) exceeds 260 characters git fails. It's common problem on windows.
But there's a way to deal with long filenames and many modern programs know how to work with long names.

Here's an explanation: http://blogs.msdn.com/b/bclteam/archive/2007/02/13/long-paths-in-net-part-1-of-3-kim-hamilton.aspx

Please, teach git for Windows deal with long filenames.

**Comment by kusma** [comment]
Already fixed: https://github.com/msysgit/git/commit/8439375065bebbc6ba6850cf164c9b206efe4676
