### ISSUE TITLE
git svn clone not working - unable to remap error message

### ISSUE THREAD

**Issue by monkeyrunner** [msysgit/msysgit#277]
On my work Windows 7 machine using Git Bash I am trying to clone a svn repo but keep getting the error below.

$ git svn clone -rXXXX http://XXXXXX

Initialized empty Git repository in c:/Users/jhughe14/git_repos/trunk/.git/
C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap
C:\Program Files (x86)\Git\bin\libsvn_delta-1-0.dll to same address as parent -- 0x6D620000
      0 [main] perl.exe" 10412 sync_with_child: child 14268(0x31C) died before initialization with status code 0x1
    410 [main] perl.exe" 10412 sync_with_child: *** child state child loading dlls

**Comment by dscho** [comment]
The quickest way to get `git svn` to work for you is probably the [Vagrant way](https://github.com/msysgit/msysgit/wiki/Vagrant).

**Comment by avdyk** [comment]
Isn't it related to https://github.com/msysgit/git/issues/300 ?

**Comment by kusma** [comment]
Yep, duplicate.

**Comment by Kurtmcmurt** [comment]
Sounds like a security issue

On Friday, January 16, 2015, monkeyrunner <notifications@github.com> wrote:

> On my work Windows 7 machine using Git Bash I am trying to clone a svn
> repo but keep getting the error below.
>
> $ git svn clone -rXXXX http://XXXXXX
>
> Initialized empty Git repository in c:/Users/jhughe14/git_repos/trunk/.git/
> C:\Program Files (x86)\Git\bin\perl.exe: *** unable to remap
> C:\Program Files (x86)\Git\bin\libsvn_delta-1-0.dll to same address as
> parent -- 0x6D620000
> 0 [main] perl.exe" 10412 sync_with_child: child 14268(0x31C) died before
> initialization with status code 0x1
> 410 [main] perl.exe" 10412 sync_with_child: *** child state child loading
> dlls
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msysgit/msysgit/issues/277>.
>


-- 
Kind regards,

Kurtis Rogers

**Comment by dscho** [comment]
> Sounds like a security issue

Nope. Sounds more like MSys' hack to support the `fork()` call fails due to the intended address range already being reserved (at least partially).

**Comment by CADbloke** [comment]
Related to https://github.com/msysgit/msysgit/pull/245 ??

**Comment by monkeyrunner** [comment]
@dscho - thanks but I can't install all that on my work machine.

@avdyk - yes that does look like what it is, I'll do the same as you and download an old version.
