### ISSUE TITLE
Small problem with filename

### ISSUE THREAD

**Issue by goldfix** [msysgit/msysgit#278]
Hello!

In my repository there are a group of files with filenames that contain a "?".
I work on Windows 7 and this files is not possible chackout.

Before version Git-1.9.5-preview20141217 : this files remains in "unstage area/status". For me it's ok! I do not commit this files and thats all right!
After upgraded to version: Git-1.9.5-preview20141217: this files automatically pass in "stage area/status" and is not possible "to unstage".

tnx
p

**Comment by dscho** [comment]
See msysgit/git#296
