### ISSUE TITLE
在win10预览版中使用git1.9.5无法使用https方式clone pull push git

### ISSUE THREAD

**Issue by hainuo** [msysgit/msysgit#282]
![image](https://cloud.githubusercontent.com/assets/421861/5933503/91434728-a6fc-11e4-9702-9cc0679085d5.png)

其他的信息可以参见我在coding.net的反馈

https://coding.net/u/coding/p/Coding-Feedback/topic/18169

**Comment by sschuberth** [comment]
Next time in English, please.

**Comment by linquize** [comment]
Does it work with git:// or ssh protocol?

**Comment by sschuberth** [comment]
Please do not comment on this issue anymore. The follow-up issue (in English) is at #283 (which is also closed by now).
