### ISSUE TITLE
svn.exe is too old version.

### ISSUE THREAD

**Issue by rbtnn** [msysgit/msysgit#285]
hi.
svn.exe(v1.4) is too old version. So I think  that we should delete or upgrade svn.exe.

**Comment by sschuberth** [comment]
As "we" includes *you*, feel free to file a pull request to address this, see https://github.com/msysgit/msysgit/wiki/Subversion-is-too-old,

**Comment by rbtnn** [comment]
@sschuberth Thanks you. 

> As "we" includes you, feel free to file a pull request to address this, see https://github.com/msysgit/msysgit/wiki/Subversion-is-too-old,

l got it.

**Comment by dscho** [comment]
Please note that simply deleting something that works for *some* users, something that took several months of *somebody else*'s work is something I am unwilling to accept because it would just be a lazy cop out. I have higher standards than that.
