### ISSUE TITLE
Will msysgit use latest version of  git in next release? or next next release?

### ISSUE THREAD

**Issue by TurnOffNOD** [msysgit/msysgit#286]
Now the latest git version is 2.3.0(git-scm.com), now git version in msysgit is 1.9.5（latest msysgit:Git-1.9.5-preview20141217）.

Will msysgit use a latest version in next release? Or next next release if time is not enough?

**Comment by dscho** [comment]
As announced on the Git for Windows mailing list, we are in the process of moving to a different SDK. It will take time.

**Comment by boughtonp** [comment]
> As announced on the Git for Windows mailing list

That announcement isn't being returned by search engines, so providing a link would be helpful.


> It will take time.

How much time? Days or Months?


Is there something specifically stopping v1.9.5 from being updated to 2.3.0 or is it simply that you're only focusing on the new version?
i.e. could someone else download relevant tools to build a v2 themselves, or is there a blocker preventing that?

**Comment by t-b** [comment]
@boughtonp 
Here you go: https://groups.google.com/forum/#!topic/msysgit/xmAOOAZ9ing

There is no big show-stopper in upgrading to 2.3.0. Just the usual rebase and tests fixing. If you can provide a PR with *both* parts I'm happy to merge that into master.
For the rebasing you need to use https://github.com/msysgit/msysgit/blob/master/share/msysGit/shears.sh.

Word of caution: This is not something for the faint of heart.
