### ISSUE TITLE
Reenable perl debugging

### ISSUE THREAD

**Issue by Dirk1966** [msysgit/msysgit#292]
"perl -de 1" is not possible any more.  This is basic perl and should just working, because the two files lib/perl5/5.8.8/dumpvar.pl and lib/perl5/5.8.8/perl5db.pl are in any basic perl setup and cannot be loaded afterwards via CPAN, ...

**Comment by Dirk1966** [comment]
I added pull request #292
     Reenable perl debugging #292
to solve this issue.

**Comment by Farhaaad-saaami** [comment]
Farhaaads
