### ISSUE TITLE
Can't save the status of VIEW (palettes)

### ISSUE THREAD

**Issue by platonicsolz** [msysgit/msysgit#294]
I changed the view scheme of tab via right clicking on single tab and selected palettes, but when i close terminal it does not save the selected palettes?? anyone help?

**Comment by dscho** [comment]
Ummm. This description is quite unclear... how about a [coherent description how to reproduce](http://stackoverflow.com/help/mcve)?

**Comment by sschuberth** [comment]
If you have tabs in your terminal, it mostly likely is a third-party terminal app (like ConEmu or Console Z) and not related to msysgit.

**Comment by dscho** [comment]
@sschuberth we should not guess... that is not helpful. In fact, we should not need to guess.

@platonicsolz please feel free to provide a thorough explanation what exactly did not work, and how to reproduce, and what to expect instead. Until that time, I will close the ticket (feel free to reopen it with the required information).

**Comment by sschuberth** [comment]
> In fact, we should not need to guess.

Exactly. And that's why I gave examples about what kind of information we'd expect, like whether a third-party terminal app is used, and if so, which one.

**Comment by platonicsolz** [comment]
Actually i overlooked the settings of the app, its working now.

**Comment by dscho** [comment]
> Actually i overlooked the settings of the app, its working now.

@platonicsolz please note that even that last statement managed nothing else here than to leave me puzzled. Literally *all* information is missing that could help me understand the issue you had.
