### ISSUE TITLE
Open security bugs in openssl

### ISSUE THREAD

**Issue by t-b** [msysgit/msysgit#295]
As soon as the new openssl security fixes are [out](http://marc.info/?l=openssl-users&m=142653449310870&w=2) I plan on preparing a new release of git for windows and msysgit.

**Comment by dscho** [comment]
Thanks, @t-b!

**Comment by t-b** [comment]
Done via https://github.com/msysgit/msysgit/releases/tag/Git-1.9.5-preview20150319.
