### ISSUE TITLE
Update OpenSSL to 1.0.2a

### ISSUE THREAD

**Issue by vszakats** [msysgit/msysgit#304]
As in subject. `curl` does support it, `msmtp` should do too (if not the included version 1.4.17, the latest 1.6.x almost certainly does).

**Comment by dscho** [comment]
Please. I am sure you mean well, but please, please, please use the search function before reporting a bug. It just costs us time to mark tickets as duplicates [while we're upgrading to a more modern development environment](https://github.com/git-for-windows).

**Comment by vszakats** [comment]
I see a ton of closed Issues dealing with various forms of 1.0.1 and 0.9.8 (I understand your project depends on a mixture of 1.0.1 and 0.9.8). "1.0.2" or "1.0.2a" gives no hit. Reading all the closed Issues seems a not very efficient way to get to reveal that there is completely different project in the works. Might be worth to put a mention on the front README. Thanks for the link, I'll try that new project.

**Comment by dscho** [comment]
@vszakats Well, please keep in mind that forcing me to read this issue and to close it takes time, time that I cannot spend on getting Git for Windows 2.x out of the door ;-)

**Comment by vszakats** [comment]
Sorry to bother @dscho, I promise it won't happen again and will stay being an end-user.

**Comment by dscho** [comment]
That is truly a pity. I was certain you could improve your contributions and offer valuable additions to the software you use for free.
