### ISSUE TITLE
Very slow with samba share

### ISSUE THREAD

**Issue by strauss69400** [msysgit/msysgit#306]
Hi,

I installed a machin virtual with virtualbox to work with linux.my website in hosted in this virtual machine.i create a samba share To access from windows.when i use sourcetree,the git operations are very slow because the repositories in on the samba share.is there a solutions to improve performances?
 Thanks
Sorry for my english

**Comment by shiftkey** [comment]
Could you confirm which version of Git you're using in SourceTree?

**Comment by sschuberth** [comment]
I don't think knowing the SourceTree version gets us any further as it can be configured to use either an embedded Git or the system Git.

@strauss69400 Can you instead try to reproduce the issue with pure command line Git and state the version you're using?

**Comment by strauss69400** [comment]
i use the version 1.6.14 for sourctree and the version of git is 1.8.5.2.
with pure command the problem is the same.

**Comment by dscho** [comment]
@strauss69400 I'd like to ask you to describe your workflow a bit more. If you use the VM just to host the repo, it might be better to do that in a dedicated Windows directory instead. Alternatively you might want to use VirtualBox' Shared Folders feature to avoid having to cross the network layer just to access your repository with SourceTree.

**Comment by strauss69400** [comment]
I use my vm for hosted my websites.so I have to have my repo on the vm.
if I put my sites on windows, apache server is slow.if my sites are on my vm, this is sourcetree who is slow

**Comment by dscho** [comment]
My recommendation: give shared folders a try.

**Comment by strauss69400** [comment]
Sorry but i don t understand what you say.samba share is already a shared folder

**Comment by dscho** [comment]
I am talking about https://forums.virtualbox.org/viewtopic.php?t=15868 (it is faster than Samba shares, as it is integrated into VirtualBox on the OS level).

**Comment by strauss69400** [comment]
Yes i already tried this solution.websites are hosted in host windows so git will be fast but the problem  is apache server will become slow.

**Comment by almendro** [comment]
Hello to all. First: forget me for my poor english.

I have the same problem of very-slow experience, both bash and GUI, with samba share folders over an Windows network. When I try git status it take very-long time to show, even with -one parameter.

Git version 1.9.5-preview20141217

Many thanks for this awesome tool.

Best.

**Comment by dscho** [comment]
@strauss69400 @almendro could you try [Git for Windows 2.x](http://git-for-windows.github.io/), please? If the problem persists, please [open a ticket there](http://git-for-windows.github.io/#contribute) (Git for Windows 1.x was retired in favor of focusing all my energy on the new version).

**Comment by QingqingZhou** [comment]
I can confirm that with
  - with windows client 2.12.1.windows.1 on win7/x64
  - with samba drive mapped to a very remote Linux box
the slow issue is still there. 

And the reason I believe is that git.windows treats samba drive and local drives with no difference. So if I issue a git status command, it actually loop through all files in all folders, which finally delegate to smbd process interactively.

Instead, git.windows can ssh to the samba drive's Linux box and issue git command there and get back results and examines files accordingly, which shall be much faster.  There are some details need to figure out, like parsing git output may subject to version differences etc, but it is doable.

Thoughts?
Qingqing

**Comment by sschuberth** [comment]
@QingqingZhou If Git for Windows version 2.12.1.windows.1 is affected, then you've reported to the wrong issue tracker. Please use https://github.com/git-for-windows/git/issues instead.
