### ISSUE TITLE
Can't SSH to an IPv6 host

### ISSUE THREAD

**Issue by davux** [msysgit/msysgit#307]
When trying to connect to an IPv6-only host:

    $ ssh -6 fdda:dada:dada:dada::xxxx:xxxx
    ssh: Could not resolve hostname fdda:dada:dada:dada::xxxx:xxxx: ai_family not supported

I think the error comes from `getnameinfo()`.

Please let me know if you need more information!

**Comment by t-b** [comment]
Duplicate, see https://github.com/msysgit/git/issues/131#issuecomment-71122113.
