### ISSUE TITLE
Question about encoding

### ISSUE THREAD

**Issue by tleepa** [msysgit/msysgit#308]
Not sure if this is the right place to ask this question... please, point me to the right direction if it is not...

I am using CmdEr with MSysGit package (just updated to the PortableGit-1.9.5-preview20150319 version) on Windows 7 x64.

How should I set the encoding options, so the polish characters are displayed correctly by 'ls' commands? The 'dir' command works fine (screenshot attached).
![conemu_pl](https://cloud.githubusercontent.com/assets/7734919/7318380/b1c7693e-ea8b-11e4-8611-7751c08b1991.png)
In the config file, I have all CharSet options set to Eastern Europe. When I write polish letters, they appear ok, I can use these leeters with e.g. 'cp' command and the filenames look ok in the system but not when being displayed by 'ls'.
Test filename in text: `Zażółć gęślą jaźń.txt`

**Comment by dolmen** [comment]
Tell us the output of `locale`.

**Comment by dscho** [comment]
I strongly suggest to give [the upcoming Git for Windows 2.x](https://git-for-windows.github.io/) a spin. Note, however, that some development on your side might be required if it does not yet do what you need it to do.

**Comment by tleepa** [comment]
It seems that there is no `locale` command:
> 'locale' is not recognized as an internal or external command,
operable program or batch file.

As for using upcoming version of Git - I just wanted to have the basic linux commands available on Windows - like grep, ls, etc.

**Comment by dscho** [comment]
Indeed there is no MinGW `locale`.

> I just wanted to have the basic linux commands available on Windows - like grep, ls, etc.

Sorry, this is the *Git for Windows* project. If you are looking for basic Linux commands, Linux is top choice. If you are actually referring to GNU tools, you are probably better served by installing yourself a Cygwin, or an MSys2.

Thanks for clarifying!
