### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by rk08** [msysgit/msysgit#312]
hi,

I am using windows 7, when i download and try to install from this link https://windows.github.com/index.html I see the following error, can you guys tell me how to fix it  

![image](https://cloud.githubusercontent.com/assets/1699943/7755851/e0f31f82-ffbc-11e4-90eb-52e730137c44.png)

**Comment by dscho** [comment]
Do you mean GitHub for Windows?

**Comment by rk08** [comment]
Yes

**Comment by dscho** [comment]
Wrong project, then...  See [this page](https://windows.github.com/help.html) to find out how to get answers about GitHub for Windows.
