### ISSUE TITLE
pass integration?

### ISSUE THREAD

**Issue by MaxNoe** [msysgit/msysgit#313]
One of the standard tools on unix machines is the password manager `pass`.

An integration of this into the git bash environment would be awesome!

http://www.passwordstore.org/

**Comment by dscho** [comment]
It is a dangerous path to go down, if we were to start including Unix tools left or right. Providing Unix tools is outside the purview of *Git for Windows*.

If you want to have Unix tools available on Windows, I suggest you turn to [MSys2](https://msys2.github.io/) or [Cygwin](https://cygwin.com).

In fact, if you want to use the `passwordstore` package with MSys2, a splendid way would be to add support to, and open a Pull Request for, MSys2's [MINGW-packages](https://github.com/Alexpux/MINGW-packages) or its [MSYS2-packages](https://github.com/Alexpux/MSYS2-packages) project.
