### ISSUE TITLE
Cannot clone repo over http: fatal: unable to access: The requested URL returned error: 403

### ISSUE THREAD

**Issue by fracz** [msysgit/msysgit#315]
When using msysgit `Git-1.9.5-preview20150319` it is impossible to clone repository that is served with [Gerrit](https://code.google.com/p/gerrit/) over HTTP. 

```
$ git clone http://myusername@myGerrit.com:10002/my-repo
Cloning into 'my-repo'...
fatal: unable to access 'http://myusername@myGerrit.com:10002/my-repo': The requested URL returned error: 403
```

After downgrading to `Git-1.9.5-preview20141217` everything works.

I inspect access logs on my server and they are as follows.

`Git-1.9.5-preview20150319`:
```
185.28.251.241 - - [28/May/2015:19:31:17 +0200] "GET /my-repo/info/refs?service=git-upload-pack HTTP/1.1" 401 458 "-" "git/1.9.5.msysgit.1"
185.28.251.241 - - [28/May/2015:19:31:22 +0200] "GET /my-repo/info/refs?service=git-upload-pack HTTP/1.1" 403 290 "-" "git/1.9.5.msysgit.1"
```

`Git-1.9.5-preview20141217`
```
185.28.251.241 - - [28/May/2015:19:42:08 +0200] "GET /my-repo/info/refs?service=git-upload-pack HTTP/1.1" 401 458 "-" "git/1.9.5.msysgit.0"
185.28.251.241 - - [28/May/2015:19:42:08 +0200] "GET /my-repo/info/refs?service=git-upload-pack HTTP/1.1" 200 1193 "-" "git/1.9.5.msysgit.0"
185.28.251.241 - - [28/May/2015:19:42:08 +0200] "POST /my-repo/git-upload-pack HTTP/1.1" 200 80403 "-" "git/1.9.5.msysgit.0"
```

I have also described the issue on StackExchange: [Cannot clone repo on windows fatal: unable to access. The requested URL returned error: 403](http://superuser.com/questions/920563/cannot-clone-repo-on-windows-fatal-unable-to-access-the-requested-url-returned/920865#920865)

**Comment by dscho** [comment]
Could you try the release candidate for [Git for Windows 2.x](https://git-for-windows.github.io/), please?

**Comment by fracz** [comment]
Wow, great to hear that it's out!

Indeed, [Git for Windows 2.x](https://git-for-windows.github.io/) clones the repo without a problem, too. So it seems that only `Git-1.9.5-preview20150319` is affected.

**Comment by dscho** [comment]
Thanks for confirming! I will close this ticket because MSys1-based Git for Windows will be deprecated soon, anyway.
