### ISSUE TITLE
Windows, path name ending with a dot [UPDATED, was path name too long]

### ISSUE THREAD

**Issue by maxferrario** [msysgit/msysgit#317]
[EDIT]
I'm having troubles when cloning a repository on my windows box, apparently due to a filename that's ending with a dot.

I'm using the latest git binary available from git-scm.com (git version 1.9.5.msysgit.0).

When I issue the command

    git clone repository-url directory

I get the error message

    error: Invalid path 'insanely/long/path/with/a/lot/of/subfolders/filename-ending-with-a-dot'

The filename shown in the error message is truncated, and I guess this is why git doesn't see that the filename is in the repository.

I have tried a few workaround, i.e.:

 1. issue the git command "git config core.longpaths true"
 2. prefix the output folder name with \\\\?\ as in \\\\?\disk:\path\to\repo\ when cloning the repo
 3. create a hard link (c:\r) and put my repo there (see http://stackoverflow.com/questions/4992577/msys-git-and-long-paths) I couldn't really try this because when I launch git clone I get the error "fatal: Invalid symlink 'c:/r': Function not implemented"
 4. I also tried the steps suggested in #122 (https://github.com/msysgit/git/pull/122#issuecomment-43653756) but when I issue the command massimo (master) git $ ./git fetch origin refs/pull/190/merge i get the error message "fatal: Couldn't find remote ref refs/pull/190/merge"

I run out of tricks/suggestions, and I'm stuck...

Do you have any suggestions?

Thanks a lot,
Massimo

**Comment by kblees** [comment]
> ```error: Invalid path```

You get this error if the path is invalid on Windows (e.g. is a short file name, ends with a space or dot, or contains invalid characters [1]). It probably has nothing to do with the length.

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx

**Comment by maxferrario** [comment]
Thanks for your reply, Karsten.
I don't think that the windows path is invalid, though: the file has been downloaded from the remote repository and I can open it on my PC
But git says that a file with a similar, truncated name has been deleted from my working area.
I'm not sure it is important, but the truncated filename ends with a dot (.), so I cannot even unstage it.

**Comment by kblees** [comment]
Do you get the same error with the Git for Windows 2.0 release candiadate [1]?

The "file ends with dot" check can be disabled via ```git config core.protectntfs false```, but this doesn't solve the core problem that the path gets truncated.

Do you have a public repo that can be used to reproduce the problem?

[1] http://git-for-windows.github.io

**Comment by maxferrario** [comment]
No, unfortunately I am accessing a private repo.
And yes, I have the same problem with the RC (git version 2.4.1.windows.1).

**Comment by maxferrario** [comment]
After I played a little bit with a linux box, I think I nailed down the problem: we actually have a file in the repo whose name ends with a dot, but that file cannot be created on windows because, as Karsten pointed out, that kind of path is invalid on windows.
So, to quote Karsten, this issue "has nothing to do with the length".

**Comment by vishalzanzrukia** [comment]
@maxferrario  So finally, how did you solve the problem?

**Comment by maxferrario** [comment]
hi @vishalzanzrukia , 
as the file was not needed (apparently it was an old version of a legitimate file, but nobody knows why the name was truncated ) the solution was simple: we removed it from the repository.
