### ISSUE TITLE
Can't pull when repo is in a removable drive

### ISSUE THREAD

**Issue by fidelt** [msysgit/msysgit#318]
If I try to pull from a remote repo from within a repo that is located on a removable drive, it returns the following:

/usr/libexec/git-core/git-sh-setup: line 343: cd: .git: No such file or directory
Unable to determine absolute path of git directory

Interestingly enough, I can check the status of the repo and even push, but not pull.
Version of Git is 1.9.5.msysgit.1, using MINGW32, if it helps.

EDIT: I don't know what happened, but pulling somehow works again.
I'm sure that it didn't work awhile ago, because I tried pulling from within C:\, and even network drives and the only way it had failed was if I were inside a removable drive.
I'm sorry for wasting your time.

**Comment by dscho** [comment]
If it happens again, please debug this issue further by locating the `git-sh-setup` file (it should be in `C:\Program Files (x86)\Git\usr\libexec\git-core\git-sh-setup`) and insert the line `set -x` before line 343. That should trigger the `cd` command line to be printed and should give us a better chance to understand *which* path Git thinks is not a file or directory.

**Comment by fidelt** [comment]
It has happened again, and I did what you told me to.

Here's a screenshot of the output:
![untitled](https://cloud.githubusercontent.com/assets/5409093/8561305/e8ca680a-2555-11e5-8546-379f1d8f399a.png)

I think I might have found out how it happens.
1. I right click on a local project and click "Git BASH Here" (it was a C# project but I don't think it matters)
2. Insert the external drive and navigate to the project inside the external drive. Once again, right click and click on "Git BASH Here"
3. Execute the command "git pull"

The only way I got to do a successful pull was to close all MINGW32 windows, and open them all again.

**Comment by dscho** [comment]
I just verified that this is only an issue with Git for Windows 1.x, but not with [Git for Windows 2.x](https://git-for-windows.github.io/). Besides, it is stated in the release notes that:

> Unless you define the environment variable MSYS_WATCH_FSTAB (the value must be a non-empty string), Git Bash will not see any drives that have been attached after bash was started. This is a workaround to help the speed of cmd scripts using parts of Git that are implemented as shell scripts.

**Comment by fidelt** [comment]
Thank you for your response.
I was unaware of the workaround.
Thank you also for letting me know of Git 2.x
