### ISSUE TITLE
GIT on Windows 10

### ISSUE THREAD

**Issue by carlosnpz** [msysgit/msysgit#320]
My GIT Bash is acting really strange since I updated my OS to Windows 10: I execute the comands I need, but sometimes (very often) the terminal screen freezes. It doesn't crash at all, but it's like the command is being executed forever, so I can't type anything.

I have already uninstalled and installed GIT, but the problem persists...

Anyone can help me? Did you notice this problem too? Is it going to be solved in future updates?

**Comment by dscho** [comment]
Unfortunately, this is very little information to go by:

- Do you mean the Git Bash or Git CMD when you say "the terminal screen"?
- Which commands did you try? Did you try to narrow down *which* commands display that behavior?
- Did you try to trace the calls e.g. by setting `GIT_TRACE=1`?
- Did you monitor the processes with [Sysinternals' Process Monitor](https://technet.microsoft.com/en-us/library/bb896645.aspx)?
- Did you try the same with different Windows versions?
- *Which* Git for Windows version do you use to begin with?

**Comment by dscho** [comment]
Oh, and most importantly: did you try any of the release candidates of the upcoming [Git for Windows 2.x](https://git-for-windows.github.io/), slated to supersede msysGit-based Git for Windows 1.x?

**Comment by carlosnpz** [comment]
1- I mean GIT Bash
2- I tried many commands, but this problem only happens when I execute git add --all ., git commit -m "Message", git pull origin master
3- No, I didn't
4- No, I didn't
5- Yes, this problem only started when I updated my Windows from 8.1 Pro to 10 Pro
6- I use version 1.9.5, that's the only one I ever used since I had Windows 8.1 on my machine.
7- No, I didn't try 2.X yet. Is there already a binary file link for me to try?

**Comment by dscho** [comment]
> I didn't try 2.X yet. Is there already a binary file link for me to try?

Yep. It's linked from the page I provided earlier: http://github.com/git-for-windows/git/releases/latest

**Comment by carlosnpz** [comment]
Thanks! I'll try it and post a response here.

**Comment by carlosnpz** [comment]
That worked, thank you so much!!! :D

**Comment by dscho** [comment]
Okay! Thank you for reporting back the results.

I will close this issue now because it is better to focus my efforts in 2.x than to try to figure out a fix fo 1.x that will be obsolete in a couple of weeks anyway.
