### ISSUE TITLE
git svn rebase Or git svn dcommit   cygwin_exception

### ISSUE THREAD

**Issue by chucklu** [msysgit/msysgit#321]
After a update git for windows 2.5,I encountered this problem.
$ git svn dcommit
Committing to myUrl
      0 [main] perl 30192 cygwin_exception::open_stackdumpfile: Dumping stack trace to perl.exe.stackdump

Exception: STATUS_ACCESS_VIOLATION at rip=00000000000
rax=0000000000000000 rbx=00000006010982B8 rcx=00000006010982B8
rdx=00000006010A05F8 rsi=0000000000000011 rdi=0000000000000000
r8 =0000000000000000 r9 =00000006010C81E8 r10=0000000000230000
r11=000000049F2420D9 r12=000000000022C080 r13=000000000022C088
r14=000000060108F308 r15=000000060108F278
rbp=000000000022C098 rsp=000000000022C028
program=C:\Program Files\Git\usr\bin\perl.exe, pid 18752, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
End of stack trace

**Comment by dscho** [comment]
Please report the bug in the new org (msysgit is retired), according to http://git-for-windows.github.io/#contribute.

Also, please provide more information about your system. In particular whether you installed the portable or the non-portable version, 32-bit/64-bit, Windows version, example Subversion repository to reproduce the problem.

**Comment by dscho** [comment]
Oh, and maybe it is related to https://github.com/git-for-windows/git/issues/274?
