### ISSUE TITLE
core.autocrlf default setting

### ISSUE THREAD

**Issue by vincentb1** [msysgit/msysgit#322]
No sure whether this problem is still there, or ever was. I am using git on MSW 7. I think that this is from MSYS git because when I open the git bash console and I type `pwd -W` there is no error. Another test is to type `perl -e 'print "$^O"'` and the output is `msys`.

So, my problem is that the setting `core.autocrlf` was true at system level. I don't think that I have done this setting myself, or I completely forgot that, but I think it has been this way since installation.

I don't think that this is a good idea to activate LF to CRLF translation by default for text files, that can cause problems when you pull open source projects that rely on keeping the EOL as there are in the repo. 

Most modern editors on MSW accept the LF EOL without any barking and keep it after a an edit.

**Comment by dscho** [comment]
You probably want to upgrade to [Git for Windows 2.x](https://git-for-windows.github.io/); *This* project (Git for Windows 1.x) is no longer maintained.
