### ISSUE TITLE
Bash colorization

### ISSUE THREAD

**Issue by boxfoot** [msysgit/msysgit#323]
Hi,

I'm having an issue with colorized output in my bash shell, and noticing differences when I run `\Program Files\Git\bin\bash.exe` versus `\Program Files\Git\git-bash.exe`

In BOTH of these shells, my basic shells and prompts colorize properly.  However, when I run commands in the shell, the are correctly colorized in `Git\bin\bash.exe` and not colorized in `Git\git-bash.exe`

`bin\bash.exe`:
![image](https://cloud.githubusercontent.com/assets/487130/12145108/e2e1acc4-b451-11e5-88b4-300294b63c47.png)

`git-bash.exe`:

![image](https://cloud.githubusercontent.com/assets/487130/12145086/c8607ee8-b451-11e5-975c-c804e43d3bbd.png)

I'm running Git for Windows v2.6.3.

Any idea what's going on or how I can fully colorize `git-bash.exe` (which is an otherwise more feature-complete shell)?

**Comment by dscho** [comment]
> I'm running Git for Windows v2.6.3.

Then this bug tracker is the wrong one. You want to go here instead: https://github.com/git-for-windows/git/issues.

**Comment by boxfoot** [comment]
Oops - sorry about that!
