### ISSUE TITLE
Should `vi` launch `vim` by default?

### ISSUE THREAD

**Issue by ivanbportugal** [msysgit/msysgit#326]
I tried this on a clean windows machine... No git. No node. Just cmder with git. The objective is to be able to use git within cmder _and_ be able to use vi as the editor for git rebase interactive mode, plain text editing, etc...

Right now I have to set an alias which is fine but is that the intent or am I covering up a minor bug?
![vialias](https://cloud.githubusercontent.com/assets/1224284/12928924/d894ee6c-cf35-11e5-8fa1-efbed0257eaa.gif)

**Comment by ivanbportugal** [comment]
I apologize. This is an issue/workaround for cmder, not mysysgit (https://github.com/cmderdev/cmder/)

**Comment by dscho** [comment]
Please also note while it is much, much easier for you to simply paste an animated GIF, it makes it much, much more difficult for everybody else to follow what is going wrong than a clearly written bug report.
