### ISSUE TITLE
git bash remember password

### ISSUE THREAD

**Issue by simonbaker** [msysgit/msysgit#328]
how can git bash remember password??
because every time I pull or push,git bash want me to enter password.
and I had try some ways,but cant resolve my problem.
some ways like:
1 http://stackoverflow.com/questions/22267764/automatically-cache-git-credentials-from-a-windows-batch-script
2 http://stackoverflow.com/questions/19029987/git-asks-for-password-for-each-commit-and-pull/19030243#19030243
3 http://my.oschina.net/u/140714/blog/193557?fromerr=PvubNd96

**Comment by dscho** [comment]
1. This project is no longer maintained, but has been superseded by [Git for Windows 2.x](https://git-for-windows.github.io/)
2. This is not a bug report, but a request for assistance. Further, it is not at all specific to Windows. As such, you need to send this to [the Git mailing list](mailto:git@vger.kernel.org).

**Comment by simonbaker** [comment]
ok,thanks.

**Comment by simonbaker** [comment]
The email cant send success.
see:
无法发送到 git@vger.kernel.org
退信原因	未知原因 
host vger.kernel.org[209.132.180.67] said: 553 5.7.1 Hello [14.17.44.33], for your MAIL FROM address <675036196@qq.com> policy analysis reported: Your address is not liked source for email (in reply to MAIL FROM command)

**Comment by simonbaker** [comment]
I had create a new issue,https://github.com/git-for-windows/git/issues/688

**Comment by dscho** [comment]
> The email cant send success.

Maybe you need to get an email address that looks less like a spammer to the Git mailing list administrators.
