### ISSUE TITLE
Missing Documentation/Information on Switches to use to install options after components.

### ISSUE THREAD

**Issue by polliard-jmfe** [msysgit/msysgit#334]
Not being familiar with the install.iss, I can't seem to find the right switches to enable some standard behavior that is desired in our setup.

Is there any documentation on what switches will: 
- Use Git and Optional Unix tools from the windows command prompt
- Checkout Windows-Style, commit unix-style endings. (While this is the default, want to enforce in case it ever changes.)
- Use MINtty
- etc...

Thank you for any direction you can provide.

**Comment by dscho** [comment]
This is obviously the wrong bug tracker. `msysgit` is not only retired, it also is the _development environment to develop Git for Windows 1.x_. Not Git for Windows. The development environment to build it.

Besides, the issue described here is more like a request for assistance, not a bug report. It would be much better to send these questions to one of the mailing lists/forums listed at https://git-scm.com/community.
