### ISSUE TITLE
Windows, Pathname too long (>256 chars)

### ISSUE THREAD

**Issue by nitram509** [msysgit/msysgit#52]
Using *current version of msysgit for Windows (Win7 64bit), there is a big issue when
having pathnames longer than 256 characters. 

The problem occurs, if git have to handle files with such an long path name.
Than, there will be "internal errors" poping up: "File or path name too long".
After that, thing getting more and more worse.

---

I did some investigations.

It seems, that the underlying "old" cygwin has some influence.

My test setup is Windows7 64bit "Git version 1.7.8-preview20111206". (also current one)
I've created some source folders with a length of 260+ long path names.
"git add" shows the following error:
fatal: unable to stat 'Adobe InDesign CS6 Server SDK/tools/benchmark/BenchmarkChartsConsole/src/com/adobe/ids/benchmark/
samples/dce/source/suribachi/src/suribachi/api/vo/action/tools/benchmark/BenchmarkChartsConsole/src/BenchmarkChartsConso
le-app.xml': No such file or directory
Of course, this file exists but has a long path.

Additionally I've tested this command ing Git bash:
"find . | wc -L"
Pops up this error (and much more):
find: ./Adobe InDesign CS6 Server SDK/tools/benchmark/BenchmarkChartsConsole/src/com/adobe/ids/benchmark/samples/samplec
lient-java-soap/src/com/adobe/ids/samples/sampleclient-aspnet-soap/sampleclient-aspnet-vb-soap/Default.aspx.vb: File or
path name too long

Than I've checked the find command within cygwin (CYGWIN_NT-6.1-WOW64 momo 1.7.15(0.260/5/3) 2012-05-09 10:25 i686 Cygwin)
Again "find . | wc -L" ... no errors,
result : 299

My blind guess:
So maybe just linking git against a newer cygwin should work?

Any help is appreciated, to get GIT work with long path names.

**Comment by fliegera** [comment]
Is this really solved? I am working on Version 1.9.4 and facing the same Problem, when Path-lenght is > 260

**Comment by Tibor17** [comment]
no issue with 1.9.5 +1

**Comment by nitram509** [comment]
nope, still not working :-1: 

````
user@host /g/Temp/0001 (master)
warning: unable to access '0002/0003/0004/0005/0006/0007/0008/0009/0010/0011/0012/0013/0014/0015/0016/0017/0018/0019/0020/0021/0022/0023/0024/0025/0026/0027/0028/0029/0030/0031/0032/0033/0034/0035/0036/0037/0038/0039/0040/0041/0042/0043/0044/0045/0046/0047/0048/0049/.gitignore': Filename too long
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        0001.txt

nothing added to commit but untracked files present (use "git add" to track)


$ git --version
git version 1.9.5.msysgit.0

$ uname -a
MINGW32_NT-6.2 HOST 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown

Windows 8.1 Professional 64bit 
````

**Comment by shiftkey** [comment]
@nitram509 what does this return for your repository?

> git config core.longpath

**Comment by nitram509** [comment]
@shiftkey 
thanks for pointing this config option out.

Before, the **core.longpaths** wasn't set.
After I set ````git config core.longpaths true```` I was able to commit.

Good Job! Thanks everybody. :+1:

**Comment by dscho** [comment]
@nitram509 your job is not quite done yet. The best place we could come up to tell users about the longpaths feature was the release notes, but obviously that message did not reach you. Therefore, you should figure out where the information about longpaths *would* have reached you and open a PR to make it so.

**Comment by Tibor17** [comment]
setting with --global just once
git config --global core.longpath

**Comment by dscho** [comment]
@Tibor17 no, this is not what I am talking about.

Look, users will not find this bug report, let alone your comment. We need to do a substantially better job than throwing out two short lines that are unclear.

We need documentation *where users see it*, and we need documentation *that is easy to understand and enjoyable to read*.

I believe that you tried to help, but I am convinced that we need somebody to contribute something well-crafted, and thought through, to achieve our common goal to make Git for Windows easier to use. At least that goal is what I think you and I have in common, yes?

**Comment by Tibor17** [comment]
What are you trying to tell me, that i should shut my mouth. Listen to
yourself first and then say something
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dscho** [comment]
@Tibor17 and now let's spend all that energy on contributing top quality patches.

**Comment by the-Arioch** [comment]
> The best place we could come up to tell users about the longpaths feature was the release notes, but obviously that message did not reach you

Actually that could not be a good place. RelNotes are sometimes read before the upgrade, but no new user would have any reason to read them.

This belong to places like System Requirements/Limitations or FAQ or Typical Errors

And this belong to the very error messages GIT shows when meeting long paths - it has to suggest user to read about the aforementioned config option,

---

This said, why just not default it on and make the alerting of users unnecessary ?

**Comment by the-Arioch** [comment]
> we need documentation that is easy to understand and enjoyable to read.

Actually, everyone needs documentation that is informative. And after that, with lesser priority, are ease and pleasure.

So, why this option was not defaulted? What are cons and pros, what are gotchas ?

**Comment by the-Arioch** [comment]
@dscho my uneducated guess is that you failed to diff @nitram509  and @Tibor17 :-D

**Comment by dscho** [comment]
> This said, why just not default it on and make the alerting of users unnecessary ?

I wanted to be very careful to avoid problems. Please keep in mind that even the Explorer cannot handle files with too-long filenames – not even delete them.

**Comment by dscho** [comment]
> And this belong to the very error messages GIT shows when meeting long paths - it has to suggest user to read about the aforementioned config option,

@the-Arioch you could always give it a shot and implement it. Historically, well-designed Pull Requests were handled quickly and command the respect of the maintainers. It was not unheard of features being included that the maintainers were unsure about at first, but their minds had been changed by excellent code contributions (which, to be honest, is much harder than simply commenting: talk is cheap :grinning:).

**Comment by kblees** [comment]
FWIW, I've just updated the respective FAQ entry (https://github.com/msysgit/msysgit/wiki/Git-cannot-create-a-filedirectory-with-a-long-path)

**Comment by dscho** [comment]
@kblees thank you for your continued top quality contributions! Believe me, I appreciate that very, very much.

**Comment by nitram509** [comment]
@kblees thank you for updating the FAQ

**Comment by natasha544** [comment]
long path tool is very helpful. thanks

**Comment by dolmen** [comment]
The wiki page has moved [here](/git-for-windows/git/wiki/Git-cannot-create-a-file-or-directory-with-a-long-path).
