### ISSUE TITLE
failure during installation

### ISSUE THREAD

**Issue by donbright** [msysgit/msysgit#56]
steps followed
1. system: Windows Vista Home Premium, Service Pack 2, AMD x64 Turion
2. installed msys, ran mingw-get update (mingw-get-inst-20120426)
3. downloaded msysGit-netinstall-1.7.11-preview20120620.exe. ran program

result:
- [new tag]         v1.7.8-rc4 -> v1.7.8-rc4
- [new tag]         v1.7.8.1   -> v1.7.8.1
- [new tag]         v1.7.8.2   -> v1.7.8.2
- [new tag]         v1.7.8.3   -> v1.7.8.3
- [new tag]         v1.7.8.4   -> v1.7.8.4
- [new tag]         v1.7.8.5   -> v1.7.8.5
- [new tag]         v1.7.8.6   -> v1.7.8.6
- [new tag]         v1.7.9     -> v1.7.9
- [new tag]         v1.7.9-rc0 -> v1.7.9-rc0
- [new tag]         v1.7.9-rc1 -> v1.7.9-rc1
- [new tag]         v1.7.9-rc2 -> v1.7.9-rc2
- [new tag]         v1.7.9.1   -> v1.7.9.1
- [new tag]         v1.7.9.2   -> v1.7.9.2
- [new tag]         v1.7.9.3   -> v1.7.9.3
- [new tag]         v1.7.9.4   -> v1.7.9.4
- [new tag]         v1.7.9.5   -> v1.7.9.5
- [new tag]         v1.7.9.6   -> v1.7.9.6
- [new tag]         v1.7.9.7   -> v1.7.9.7
  fatal: read error: Invalid argument
  - error: Couldn't update submodule git!
    INSTALLATION ABORTED

hit 'x' on window

---
## Building and Installing Git

make: **\* No rule to make target `install'.  Stop.

---

Hello, dear Git developer.

This is a minimal MSYS environment to work on Git.

Your build failed...  Please fix it, and give feedback on the Git list.

Welcome to msysGit

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Run '/share/msysGit/add-shortcut.tcl' to add a shortcut to msysGit.
sh.exe": /git/contrib/completion/git-completion.bash: No such file or directory
sh.exe": __git_ps1: command not found

me@mycomputer /git

msysGit-netinstall-1.7.11-preview20120620

**Comment by DNTech** [comment]
**Is their any way to fix the issue during msysgit installation??** which says build failed...
I'm using windows7 and want to use git-ftp...
**should I place a new issue??**

**Comment by sschuberth** [comment]
The _msysgit_ project has been superseded by the _Git for Windows_ project, you can get the new SDK from [here](https://github.com/git-for-windows/build-extra/releases) and the new client from [here](https://github.com/git-for-windows/git/releases). There are no plans to continue maintaining the _msysgit_ project.
