### ISSUE TITLE
SFTP remote repos - adding sftp remote helper.

### ISSUE THREAD

**Issue by sheershoff** [msysgit/msysgit#59]
Trying to push to a sftp:// remote repo returns an error `fatal: unable to find remote helper for 'sftp'`. Is there a way one can add the sftp support?

**Comment by brbrady** [comment]
Wait, but why? Link is broken. Seems like this is a reasonable request...

**Comment by dscho** [comment]
> Link is broken.

It would have been more helpful to look at the link, notice that it is broken in an obvious way and provide an *unbroken* link instead: https://stackoverflow.com/questions/9163295/cloning-a-git-repository-over-sftp/

> Seems like this is a reasonable request...

I may seem like that, but...

1. you should research that issue first. Seriously. Once you know *just how much* work it would be (the SFTP protocol is in *no* way close to the HTTPS protocol, and *that* protocol took years to support propery), you cannot agree that it is such a reasonable request anymore. You would basically spend not even ten seconds requesting something that somebody would have to spend at least 3 person-months to implement. That's just not really fair.
2. the request is not about a Windows-specific feature. But it is reported to the (awfully under-handed, pun *not* intended) Git for Windows project. If this feature request is serious (as in: the person requesting it is prepared to contribute at least as much time and skill  as they ask other to spend), it should be proposed on [the Git mailing list](mailto:git@vger.kernel.org) (which is not limited to Windows only).
