### ISSUE TITLE
Add 'Git bash here' to context menu *in* a folder

### ISSUE THREAD

**Issue by hickford** [msysgit/msysgit#84]
Git for Windows adds a 'git bash here' item to the Windows Explorer context menu, when opened on a folder.

It would be really helpful to add the 'git bash here' item for context menus opened _in_ a folder. I for one use this context menu much more often.

Example screenshot of the context menu where the item is missing http://i.imgur.com/UV9b7.png

**Comment by japsumali** [comment]
hello, how about for terminal on a mac?

**Comment by sschuberth** [comment]
This (deprecated) project is about using Git on Windows only. Mac is totally out of scope.
