### ISSUE TITLE
Git protocol hangs indefinitely.

### ISSUE THREAD

**Issue by ghost** [msysgit/msysgit#89]
I've just started building a CI server with Window Server 2012 and hit a issue where `git-push` hangs indefinitely.

Did some research and found [this](http://code.google.com/p/msysgit/issues/detail?id=457) but it appears to have been forgotten about; there's nothing on here either about it being a problem.

This is still occurring with `1.8.0.msysgit.0`.

**Comment by jtgans** [comment]
Wait, why is this closed? I just ran into this recently on 1.9.5.msysgit.1 and it /still hangs/ without the workaround flag turned on.

Can we just default this flag to true in the msysgit builds?

**Comment by dscho** [comment]
> Wait, why is this closed?

Hehe... the answer is in this ticket: https://github.com/msysgit/msysgit/issues/89#issuecomment-31365743

Are you the person driving the resolution of this issue forward? If so, I will gladly reopen (although I will insist to focus on [Git for Windows 2.x](https://git-for-windows.github.io/), which already saw the 3rd release candidate.

**Comment by jtgans** [comment]
Is this also a problem for GfW? If so, I'd be happy to send along a patch to enable the workaround by default.

**Comment by dscho** [comment]
> Is this also a problem for GfW?

I do not know; I never experienced the problem myself, so I cannot test.

**Comment by agibson-vrnt** [comment]
Seeing what looks to be the same problem in 2.8.1.windows.1

**Comment by dscho** [comment]
@agibson-vrnt see [here](https://github.com/msysgit/msysgit/issues/89#issuecomment-113878450).

**Comment by johnnyb** [comment]
I just wanted to leave a comment for those finding this page that the way to work around it is by running this command:

git config --global sendpack.sideband false
